[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
target-applies-to-host = false
panic-abort-tests = true

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static", "-C", "link-arg=-no-pie"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"